---
name: Building Desktop
on:
  pull_request:
    branches:
      - aurora
    paths-ignore:
      - "**.md"
  schedule:
    - cron: '31 6 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - aurora
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Aurora"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
